require('nvim.core.options')
require('nvim.core.keymaps')
require('nvim.core.plugins')
require('nvim.core.colorscheme')

require('nvim.plugins.alpha')
require('nvim.plugins.auto-session')
require('nvim.plugins.autopairs')
require('nvim.plugins.bufferline')
require('nvim.plugins.cmp')
require('nvim.plugins.colorizer')
require('nvim.plugins.comment')
require('nvim.plugins.dressing')
require('nvim.plugins.fidget')
require('nvim.plugins.gist')
require('nvim.plugins.git-blame')
require('nvim.plugins.gitsigns')
require('nvim.plugins.illuminate')
require('nvim.plugins.indentline')
require('nvim.plugins.lsp')
require('nvim.plugins.lspsaga')
require('nvim.plugins.lualine')
require('nvim.plugins.matchup')
require('nvim.plugins.notify')
require('nvim.plugins.numb')
require('nvim.plugins.nvim-tree')
require('nvim.plugins.nvim-webdev-icons')
require('nvim.plugins.project')
require('nvim.plugins.session-manager')
require('nvim.plugins.tabout')
require('nvim.plugins.telescope')
require('nvim.plugins.todo-comments')
require('nvim.plugins.toggleterm')
require('nvim.plugins.treesitter')
require('nvim.plugins.which-key')
-- TODO: Enable this once Neovim > 0.8 is available
-- require('nvim.plugins.lsp-inlayhints')
