-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
return {
  kind = {
    Class = ' ',
    Color = ' ',
    Constant = ' ',
    Constructor = '',
    Enum = ' ',
    EnumMember = ' ',
    Event = ' ',
    Field = ' ',
    File = ' ',
    Folder = ' ',
    Function = ' ',
    Interface = ' ',
    Key = ' ',
    Keyword = ' ',
    Method = ' ',
    Misc = ' ',
    Module = ' ',
    Operator = ' ',
    Property = ' ',
    Reference = ' ',
    Snippet = ' ',
    Struct = ' ',
    Text = ' ',
    TypeParameter = ' ',
    Unit = ' ',
    Value = ' ',
    Variable = ' ',
  },
  type = {
    Array = ' ',
    Boolean = ' ',
    Null = ' ',
    Number = ' ',
    Object = ' ',
    String = ' ',
  },
  documents = {
    File = ' ',
    Files = ' ',
    Folder = ' ',
    OpenFolder = ' ',
  },
  git = {
    Add = ' ',
    Diff = ' ',
    Ignore = ' ',
    Mod = ' ',
    Octoface = ' ',
    Remove = ' ',
    Rename = '',
    Repo = ' ',
  },
  ui = {
    ArrowClosed = '',
    ArrowOpen = '',
    BigCircle = ' ',
    BigUnfilledCircle = ' ',
    BookMark = ' ',
    Bug = ' ',
    Calendar = ' ',
    Check = ' ',
    ChevronRight = ' ',
    Circle = ' ',
    Close = ' ',
    CloudDownload = ' ',
    Code = ' ',
    Comment = ' ',
    Dashboard = ' ',
    Fire = ' ',
    Gear = ' ',
    History = ' ',
    Lightbulb = ' ',
    List = ' ',
    Lock = ' ',
    NewFile = ' ',
    Note = ' ',
    NoteBook = ' ',
    Package = ' ',
    Pencil = ' ',
    Project = ' ',
    Search = ' ',
    SignIn = ' ',
    SignOut = ' ',
    Table = ' ',
    Telescope = ' ',
    bufferline = {
      Close = ' ',
      Indicator = '▎',
      LeftTrunc = ' ',
      Modified = '● ',
      RightTrunc = ' ',
    },
  },
  diagnostics = {
    Error = ' ',
    Hint = ' ',
    Information = ' ',
    Question = ' ',
    Warning = ' ',
  },
  misc = {
    CircuitBoard = ' ',
    Package = ' ',
    Robot = ' ',
    Smiley = ' ',
    Squirrel = ' ',
    Tag = ' ',
    Watch = '',
  },
}
